MODEL:
    CKPT_PATH: './pretrained/sam/sam_vit_h_4b8939.pth'
    DEVICE: 'cuda:1'
MASK_GENERATOR:
    PTS_PER_SIDE: 32
    PTS_PER_BATCH: 64
    PRED_IOU_THRESH: 0.88
    STABILITY_SCORE_THRESH: 0.95
    STABILITY_SCORE_OFFSET: 1.0
    BOX_NMS_THRESH: 0.7
    CROP_N_LAYERS: 0
    CROP_NMS_THRESH: 0.7
    CROP_OVERLAP_RATIO: 0.3413333
    CROP_N_POINTS_DOWNSCALE_FACTOR: 1
    POINT_GRIDS: None
    MIN_MASK_REGION_AERA: 200
    OUTPUT_MODE: 'binary_mask'
LOG:
    SAVE_DIR: './log'
    LEVEL: INFO
